@startuml
' 左から右の順序：不快ワード → 自分 → 快適ワード
participant fukai as fukai
actor 自分 as self
participant kaiteki as kaiteki

== meet ==

fukai -> self : tipa,kuso,wakewakaran yokomoji
fukai -> self : youtube de ironna douga\n miteruto yokomozi wo futuuni muisiki\n nitukatteru
kaiteki -> self : zibun to dousedai ka soreyori\n uenosedaikaraha amarikannzinai

== seiri ==

self -> self : nihongo taisetuni sitai
self -> self : naze fukai ninarunoka?
self -> self : zidaini tuiteikenai?

== taisaku ==

self -> fukai: kinisinai
self -> kaiteki: kaitekina douga sika minai

@enduml